### ISSUE TITLE
add testing script

### ISSUE THREAD

**Issue by GeauxEric** [Yeahhhh/geauxdock_cs_v2#1]
Is it possible to have any scripts that enable _one-key_ testing for docking given the _ff_, _sdf_, _pdb_ files?

**Comment by Yeahhhh** [comment]
How about command-line arguments like this?
./rundock.py xxx.pdf yyy.sdf zzz.ff

essentially, we must provide information to generate the following example input files:
lig.txt:
1a07C1 /worka/work/yfang11/geauxdock_cs_v2/data/astex/ligands/1a07C1.sdf /worka/work/yfang11/geauxdock_cs_v2/data/astex/ligands/1a07C1-0.8.ff

prt.txt:
1a07C /worka/work/yfang11/geauxdock_cs_v2/data/astex/proteins/1a07C.pdb

**Comment by GeauxEric** [comment]
The scripts are still under the development for the generation of the _sdf_ and _ff_ files.
I was asking for some temporary work around for the ease of debugging and development.

**Comment by Yeahhhh** [comment]
done.

cd geauxdock_cs_v2/test
./rundock.py ./dock 1a07C-1.pdb 1a07C1.sdf 1a07C1-0.8.ff
